# -*- coding: utf-8 -*-
"""Armazenamento de Senha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxAcrQBKPYhCg_mSKnj0qf894zBQjoQj
"""

usuarios = {
    "john": "guitarra",
    "kevin": "sla"
}

def autenticar(nome, senha):
    if nome in usuarios and usuarios[nome] == senha:
        return "Autenticado com sucesso!"
    else:
        return "Falha na autenticação."

print(autenticar("john", "guitarra"))

!pip install bcrypt

import bcrypt

usuarios = {"john": bcrypt.hashpw(b"guitarra", bcrypt.gensalt()),
           "kevin": bcrypt.hashpw(b"sla", bcrypt.gensalt())}

def autenticar(nome, senha):
    if nome in usuarios and bcrypt.checkpw(senha.encode('utf-8'), usuarios[nome]):
        return "Autenticado com sucesso!"
    else:
        return "Falha na autenticação."

# Teste
print(autenticar("kevin", "sla"))